"""
English (US) language messages.
"""

MESSAGES = {
    # Common
    "title": "Network Vulnerability Scanner & Risk Assessment System",
    "welcome": "Welcome to Vulnerability Scanner",
    "error": "Error",
    "success": "Success",
    "warning": "Warning",
    "info": "Info",

    # Navigation
    "dashboard": "Dashboard",
    "new_scan": "New Scan",
    "history": "History",
    "settings": "Settings",

    # Dashboard
    "total_scans": "Total Scans",
    "hosts_scanned": "Hosts Scanned",
    "vulns_found": "Vulnerabilities Found",
    "critical_hosts": "Critical Hosts",
    "recent_scans": "Recent Scans",

    # Scan
    "scanning": "Scanning",
    "scan_target": "Scan Target",
    "discovery_method": "Discovery Method",
    "port_range": "Port Range",
    "start_scan": "Start Scan",
    "stop_scan": "Stop Scan",

    # Status
    "pending": "Pending",
    "running": "Running",
    "completed": "Completed",
    "failed": "Failed",

    # Scan Details
    "scan_details": "Scan Details",
    "host_list": "Host List",
    "service_list": "Service List",
    "vulnerability_list": "Vulnerability List",

    # Host
    "ip_address": "IP Address",
    "hostname": "Hostname",
    "mac_address": "MAC Address",
    "os": "Operating System",
    "services": "Services",

    # Service
    "port": "Port",
    "protocol": "Protocol",
    "service_name": "Service Name",
    "product": "Product",
    "version": "Version",

    # Vulnerability
    "cve_id": "CVE ID",
    "severity": "Severity",
    "cvss": "CVSS Score",
    "description": "Description",
    "affected_products": "Affected Products",
    "solution": "Solution",

    # Risk
    "risk_score": "Risk Score",
    "risk_level": "Risk Level",
    "risk_critical": "Critical",
    "risk_high": "High",
    "risk_medium": "Medium",
    "risk_low": "Low",
    "risk_info": "Info",

    # Report
    "report_title": "Network Vulnerability Scan Report",
    "executive_summary": "Executive Summary",
    "host_inventory": "Host Inventory",
    "vulnerability_details": "Vulnerability Details",
    "export_report": "Export Report",
    "print_report": "Print Report",
    "generated_by": "Generated by",

    # Actions
    "view_details": "View Details",
    "download": "Download",
    "delete": "Delete",
    "refresh": "Refresh",
    "cancel": "Cancel",
    "confirm": "Confirm",

    # Progress
    "host_discovery": "Host Discovery",
    "service_scan": "Service Scan",
    "verification": "Vulnerability Verification",
    "vuln_match": "Vulnerability Matching",
    "risk_scoring": "Risk Scoring",
    "report_gen": "Report Generation",
    "complete": "Scan Complete",

    # Messages
    "scan_started": "Scan has started",
    "scan_completed": "Scan completed",
    "scan_failed": "Scan failed",
    "no_hosts_found": "No hosts found",
    "no_vulns_found": "No vulnerabilities found",
    "report_saved": "Report saved to",
    "root_required": "Root privileges required for scanning",
}
